### ISSUE TITLE
Issue with not matched HTML tags

### ISSUE THREAD

**Issue by jlucasp25** [fabge/crispy-daisyui#5]
Hey!

I've had some troubles with rendering a couple of fields, it seems like some HTML templates have closing <div> tags but don't open and vice versa. That gives some problems and ends up ruining some form layouts.

The `select.html` file has a closing div tag without any one that opens.
The `radioselect.html` has a closing div tag outside of the for loop.

I'll be on the look out for more fields.

**Comment by fabge** [comment]
fixed in the newest version (also on pypi)
https://github.com/fabge/crispy-daisyui/releases/tag/v0.5

thanks for the heads up!

**Comment by jlucasp25** [comment]
It seems some issues still arise as after the first input is rendered, the wrapping element is closed, be it a <form> or <div> and all the following fields are rendered outside of the outside element.

**Comment by fabge** [comment]
not sure where exactly you mean. feel free to submit a pull request!
